sudo: required
services:
  - docker

script:
  - docker build -t sturmb/node .
  - docker images sturmb/node

before_deploy:
  - docker login -u sturmb -p '1IY$bO68Q7C!WGLk'

deploy:
  provider: script
  script: docker push sturmb/node
  on:
    branch: master
